### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by kubaboski** [voicis/nodebb-plugin-sso-battle.net#1]
Hi, I get this error on callback
/auth/battlenet/callback
Internal server error

```
16/12 18:04 [9605] - [31merror[39m: /auth/battlenet/callback
 AuthorizationError: Internal server error
    at OAuth2Strategy.authenticate (/opt/bitnami/apps/gadia/htdocs/node_modules/passport-oauth2/lib/strategy.js:131:25)
    at attempt (/opt/bitnami/apps/gadia/htdocs/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/opt/bitnami/apps/gadia/htdocs/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/layer.js:95:5)
    at /opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/index.js:176:3)
    at router (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/index.js:312:13)
    at /opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/bitnami/apps/gadia/htdocs/node_modules/express/lib/router/index.js:330:12)
```

**Comment by voicis** [comment]
Hi, are you sure that you have configured it correctly from the admin panel (api key/secret etc.)?

Also changes to the settings are applied only after you have restarted nodebb.

Does this happen when you are creating a new user or associating already an existing one or during log in?

**Comment by kubaboski** [comment]
Hello,
credentials are ok, even now I've made new ones and the effect is the same. The node was rebuild and restarted each every time. 

On creating new user this happens, when I finish my auth on the battle.net page
On logging in when I click the button

Look: http://gadia.pl/login

**Comment by voicis** [comment]
Looks like the callback url might be the issue, it is http (not https). OAuth requires SSL.

**Comment by kubaboski** [comment]
Ok, I've changed to https seems it's better and it should work, I will check it later.

A tip: This kind of integration could be nice: https://xenforo.com/community/resources/steam-authentication-integration.1336/

**Comment by kubaboski** [comment]
Ok, checked it, now it works.
