### ISSUE TITLE
Error: Failed to lookup view

### ISSUE THREAD

**Issue by antoine-pous** [voicis/nodebb-plugin-sso-battle.net#2]
Hi!

I would like use your plugin on NodeBB 1.4.6 but when i'm trying to access to the ACP i have this error.

```
27/4 00:15:55 [22845] - error: /admin/plugins/sso-battlenet
 Error: Failed to lookup view "admin/plugins/sso-battlenet" in views directory "/build/public/templates"
    at Function.render (/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/node_modules/express/lib/response.js:966:7)
    at content (/src/middleware/render.js:70:15)
    at /node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/node_modules/async/lib/async.js:233:13)
    at _parallel (/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/node_modules/async/lib/async.js:731:9)
    at async.waterfall.str (/src/middleware/render.js:65:12)
    at fn (/node_modules/async/lib/async.js:746:34)
    at /node_modules/async/lib/async.js:1213:16
    at /node_modules/async/lib/async.js:166:37
    at /node_modules/async/lib/async.js:706:43
    at /node_modules/async/lib/async.js:167:37
    at Immediate.<anonymous> (/node_modules/async/lib/async.js:1206:34)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by voicis** [comment]
Hi,
I just tried it on fresh NodeBB 1.4.6 install and it seem to work fine.
Can you check if the "nodebb-plugin-sso-battle.net" is referenced in the package.josn? It seems that the problem could be caused by nodebb not finding the plugin during its build process.

**Comment by antoine-pous** [comment]
I don't know why but the plugin works now...
