### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by jdutriaux** [voicis/nodebb-plugin-sso-battle.net#6]
Hello, when I try to log in with battle.net, NodeBB crashes with this error : 

```
15/11 11:50:09 [26497] - [31merror[39m: /auth/battlenet/callback
 TokenError: Internal server error
    at OAuth2Strategy.parseErrorResponse (/data/www/nodebb/node_modules/passport-oauth2/lib/strategy.js:329:12)
    at OAuth2Strategy._createOAuthError (/data/www/nodebb/node_modules/passport-oauth2/lib/strategy.js:376:16)
    at /data/www/nodebb/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /data/www/nodebb/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/data/www/nodebb/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/data/www/nodebb/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
15/11 11:51:33 [26497] - [31merror[39m:  ReferenceError: InternalOAuthError is not defined
    at /data/www/nodebb/node_modules/nodebb-plugin-sso-battle.net/library.js:101:34
    at ClientRequest.<anonymous> (/data/www/nodebb/node_modules/oauth/lib/oauth2.js:162:5)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:385:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
15/11 11:51:33 [26497] - [32minfo[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
```

I checked my configuration and everything seems fine, I'm using NodeBB 1.6.1 maybe this plugin is not compatible with this version of NodeBB?

Thanks for your help and thank you for making this plugin that could be really useful :smile:

**Comment by voicis** [comment]
Fixed the issue with missing reference to InternalOAuthError and it should not hide the actual authentication error anymore. Please try the new version of the plugin and check if that fixes your issue.

I tested it on NodeBB 1.6.1 and it was working for me. Also configuration changes are only applied after forum restart so, the configuration that is actually used might not be the same you see in the admin panel (if you have not restarted forum).

**Comment by jdutriaux** [comment]
Tested now, and it works :)!

Thanks for the fast bugfix!
